title: Hello, world! I'm Greer Homer
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
# baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
baseurl: "/portfolio" # the subpath of your site, e.g. /blog

url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Greer Homer # add your name
author-img: greer-homer.jpg # add your photo
about-author: Current data analyst and former math teacher.  
about-Grad: Master of Science in Analytics&#58 Georgia Tech (May 2021)
about-Bachelor: Bachelor of Education&#58 University of Georgia 
about-Minor: Minor in Mathematics &#58 Georgia State


# add description
# social-twitter: # add your Twitter handle
# social-facebook: # add your Facebook handle
social-github: ghomer12 # add your Github handle
social-linkedin: greer-homer-316828a6
social-email: greer.homer@gmail.com # add your Email address

# Disqus
# discus-identifier: Greer # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
